"""Tenant-scoped object storage (S3-compatible)."""

import hashlib
import re
import uuid
from collections.abc import Iterator
from functools import lru_cache
from typing import Any, Protocol
from uuid import UUID

import boto3
from botocore.config import Config
from botocore.exceptions import ClientError

from app.core.config import get_settings

MAX_UPLOAD_BYTES = 20 * 1024 * 1024
ALLOWED_CONTENT_TYPES = frozenset(
    {
        "application/pdf",
        "image/png",
        "image/jpeg",
        "image/webp",
        "text/plain",
        "text/csv",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }
)
_UNSAFE = re.compile(r"[^\w.\- ()]+", re.UNICODE)


def safe_filename(name: str) -> str:
    """A display name with no path components or control characters."""
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    cleaned = _UNSAFE.sub("_", base).strip(" .")
    return cleaned[:200] or "file"


def new_storage_key(tenant_id: UUID, area: str = "attachments") -> str:
    """Keys are generated by the server and always start with the tenant."""
    return f"{tenant_id}/{area}/{uuid.uuid4().hex}"


def sha256_of(data: bytes) -> bytes:
    return hashlib.sha256(data).digest()


class Storage(Protocol):
    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def iter_chunks(self, key: str) -> Iterator[bytes]: ...
    def delete(self, key: str) -> None: ...


class S3Storage:
    def __init__(self) -> None:
        settings = get_settings()
        self._bucket = settings.s3_bucket
        self._client: Any = boto3.client(
            "s3",
            endpoint_url=settings.s3_endpoint_url or None,
            aws_access_key_id=settings.s3_access_key,
            aws_secret_access_key=settings.s3_secret_key,
            region_name=settings.s3_region,
            config=Config(
                signature_version="s3v4",
                # A local S3 stand-in is addressed by path; AWS itself by bucket host name.
                s3={"addressing_style": "path" if settings.s3_endpoint_url else "virtual"},
                retries={"max_attempts": 3},
                connect_timeout=5,
                read_timeout=30,
            ),
        )
        # Only a local stand-in gets its bucket created on first use. A real bucket is created by its
        # owner, and the application's credentials are not allowed to list or create buckets.
        self._bucket_ready = not settings.s3_endpoint_url or settings.is_production_like

    def _ensure_bucket(self) -> None:
        if self._bucket_ready:
            return
        try:
            self._client.head_bucket(Bucket=self._bucket)
        except ClientError:
            self._client.create_bucket(Bucket=self._bucket)
        self._bucket_ready = True

    def put(self, key: str, data: bytes, content_type: str) -> None:
        self._ensure_bucket()
        self._client.put_object(Bucket=self._bucket, Key=key, Body=data, ContentType=content_type)

    def get(self, key: str) -> bytes:
        body: bytes = self._client.get_object(Bucket=self._bucket, Key=key)["Body"].read()
        return body

    def iter_chunks(self, key: str) -> Iterator[bytes]:
        body = self._client.get_object(Bucket=self._bucket, Key=key)["Body"]
        yield from body.iter_chunks(chunk_size=64 * 1024)

    def delete(self, key: str) -> None:
        self._client.delete_object(Bucket=self._bucket, Key=key)


@lru_cache
def get_storage() -> Storage:
    return S3Storage()
